@startuml
'https://plantuml.com/class-diagram

entity Product {
    id
    name
    price
}

entity Category {
    id
    name
}

entity Shop {
    id
    name
    address
    quantity
}

entity ProductShop {
    id
    id_product
    id_shop
}

entity User {
    id
    hash
    firstname
    lastname
    email
    phone
}

entity Purchase {
    id
    id_product
    id_shop
    price
    quantity
    date
}

entity UserPurchase {
    id
    id_user
    id_purchase
}

entity ProductCategory {
    id
    id_product
    id_category
}



@enduml