@startuml

entity User as user
entity user.id
entity user.firstname
entity user.lastname
entity user.nickname
entity user.email
entity user.password

user.id --* user
user.firstname --* user
user.lastname --* user
user.nickname --* user
user.email --* user
user.password --* user

entity Role
entity Grant
entity Survey
entity Questions
entity Answers
entity Action

user "1,1"--"0,*" Grant
Grant "0,*"--"1,1" Role
Grant "0,*"--"0,1" Answers
Grant "1,1"--"0,*" Survey
Survey "1,1"*--"0,*" Questions
Grant "1,1"--"0,*" Action
Survey "1,1"--"0,*" Action
Answers "0,*"--"1,1" Questions

entity Role.id
entity Role.name

entity Grant.id
entity Grant.appointed

entity Survey.id
entity Survey.title
entity Survey.description
entity Survey.state
entity Survey.created
entity Survey.answersCount

entity Questions.id
entity Questions.text
entity Questions.type

entity Answers.id
entity Answers.text

entity Action.id
entity Action.date

Role *-- Role.id
Role *-- Role.name
Grant *-- Grant.id
Grant *-- Grant.appointed
Survey *-- Survey.id
Survey *-- Survey.title
Survey *-- Survey.description
Survey *-- Survey.state
Survey *-- Survey.created
Survey *-- Survey.answersCount
Questions *-- Questions.id
Questions *-- Questions.text
Questions *-- Questions.type
Answers *-- Answers.id
Answers *-- Answers.text
Action *-- Action.id
Action *-- Action.date
Action *-- Survey.state

@enduml