@startuml
    left to right direction
    actor User as Us
    actor Admin as Adm

    package DataBaseProd{
        usecase "ID" as IDProd
        usecase "Назва товару" as NameProd
        usecase "Ціна товару" as PriseProd
        usecase "Кількість товару" as NumProd
    }

    package DataBaseUs{
        usecase "ID" as IDUs
        usecase "Ім'я користувача" as NameUs
        usecase "Кошик користувача" as BasketUs
        usecase "Картка користувача" as CartUs
        usecase "Номер телефону користувача" as NumberUs
        usecase "Пошта користувача" as EmailUs
        usecase "Історія замовлень користувача" as HistoryUs
    }

Us -u-> NameProd
Us -u-> PriseProd
Us -u-> NumProd
Us -u-> NameUs
Us -u-> NumberUs
Us -u-> EmailUs
Us -u-> HistoryUs
Us -u-> BasketUs
Us -u-> CartUs

Adm -l-> IDUs
Adm -l-> IDProd
Adm -l-> NameProd
Adm -l-> PriseProd
Adm -l-> NumProd
Adm -l-> NameUs
Adm -l-> NumberUs
Adm -l-> EmailUs
Adm -l-> CartUs

Adm -d-|> Us

@enduml